import type { Vec2 } from "../core/Entity.js";
export type { Vec2 };
export interface NavPolygon {
  readonly id: number;
  /** Convex polygon vertices in order. */
  readonly vertices: ReadonlyArray<Vec2>;
  readonly centroid: Vec2;
  /** IDs of adjacent walkable polygons. */
  readonly neighbours: ReadonlyArray<number>;
}
export interface NavMeshData {
  readonly polygons: ReadonlyArray<NavPolygon>;
}
/**
 * NavMesh pathfinding for free-form 2D movement.
 * Load a NavMeshData (generated by your level editor or Tiled plugin) then
 * call findPath() to get a smoothed waypoint list.
 */
export declare class NavMeshSystem {
  private readonly _polygons;
  load(data: NavMeshData): void;
  /**
   * Find a path between two world-space points.
   * Returns an array of waypoints starting at `from` and ending at `to`.
   * Returns [] if no path exists.
   */
  findPath(from: Vec2, to: Vec2): Vec2[];
  private _toWaypoints;
  private _nearestPolygon;
  private _pointInPolygon;
  private _dist;
  update(_dt: number): void;
}
