import fs from "fs/promises";
import path from "path";
import { evaluateEnumDecl } from "./gml/project-symbols.js";
import { scanEnums } from "./gml/scan.js";

/**
 * Real, project-wide GameMaker 2.3+ `enum Name { A, B = value, C }`
 * declarations (confirmed real against a real project's own `TRANS_MODE`
 * — `objects/obj_sidebars/Create_0.gml` — and `MSG` —
 * `objects/oTextbox/Create_0.gml` — both plain, user-authored, sequential
 * enums with no explicit member values). These are ordinary user GML code,
 * not a foreign/system constant family, and their real integer values are
 * fully statically knowable from the source alone — GameMaker's own real
 * enum semantics (confirmed via WebSearch against GameMaker's manual):
 * each member defaults to one more than the previous member's value,
 * starting at `0` for the first member; a member may instead carry an
 * explicit `= <expr>` override, and every subsequent member without its
 * own override resumes counting up from *that* value. GameMaker permits a
 * later member's `= expr` to reference an earlier member of the *same*
 * enum by name (`{ A, B = A + 4 }`) — this scanner resolves that via a
 * simple in-order evaluation against the members already computed for this
 * enum, which is the only ordering GameMaker's own parser could support
 * either (a forward reference to a not-yet-declared member is not valid
 * GameMaker GML).
 *
 * This is the enum twin of `gms2-transpile.ts`'s existing `scanGmlMacros`
 * — same "walk every `.gml` file once, project-wide, before any per-file
 * transpile" shape, since an enum declared in one object's Create event
 * (GameMaker enums are function-scoped syntactically but, per GameMaker's
 * own documented behaviour and confirmed by real projects referencing them
 * from unrelated files, are actually globally visible for the rest of the
 * project) is routinely referenced from other, unrelated objects/scripts.
 */
export async function scanGmlEnums(
  projectRoot: string,
): Promise<Map<string, Map<string, number>>> {
  const enums = new Map<string, Map<string, number>>();
  async function walk(dir: string): Promise<void> {
    let entries: string[];
    try {
      entries = await fs.readdir(dir);
    } catch {
      return;
    }
    for (const entry of entries) {
      const full = path.join(dir, entry);
      const stat = await fs.stat(full).catch(() => null);
      if (stat === null) continue;
      if (stat.isDirectory()) {
        await walk(full);
      } else if (entry.endsWith(".gml")) {
        const content = await fs.readFile(full, "utf-8").catch(() => "");
        // Declarations come from the GML lexer/parser (`gml/scan.ts`), so an
        // `enum` inside a comment or string is ignored, member bodies may
        // contain nested braces/comments, and a syntax error elsewhere in the
        // file cannot hide a declaration.
        for (const decl of scanEnums(content)) {
          if (enums.has(decl.name)) continue; // first declaration wins — real GameMaker allows only one project-wide declaration per enum name
          enums.set(decl.name, evaluateEnumDecl(decl, enums));
        }
      }
    }
  }

  await walk(projectRoot);
  return enums;
}

/**
 * Emits every scanned enum as a real, valid, plain JS `const` object —
 * `const Name = { A: 0, B: 1 } as const;` — into one shared generated
 * module every `.behavior.ts` file imports as `GmlEnums` (see
 * `gms2-transpile.ts`'s enum rewrite pass). A shared module rather than
 * per-file inlining, because an enum is genuinely project-wide data (the
 * same object identity/values everywhere), and the codebase's own
 * established precedent for project-wide generated lookups is a shared
 * module other generated files import (see e.g. `gms2-tileset-import.ts`'s
 * per-tileset modules a room's generated tilemap module imports directly)
 * rather than duplicating a growing constant table into every generated
 * file.
 */
export function buildEnumsModule(
  enums: ReadonlyMap<string, ReadonlyMap<string, number>>,
): string {
  const lines: string[] = [
    "// AUTO-GENERATED by @emptysock/toolchain's GMS2 importer. Do not edit by hand.",
    "// Real GameMaker `enum Name { ... }` declarations found project-wide, with",
    "// their real computed integer values — see gms2-enums.ts's scanGmlEnums().",
    "",
  ];
  for (const [name, members] of enums) {
    const fields = [...members.entries()]
      .map(([member, value]) => `  ${member}: ${value},`)
      .join("\n");
    lines.push(`export const ${name} = {\n${fields}\n} as const;`, "");
  }
  if (enums.size === 0) {
    lines.push("export {};", "");
  }
  return lines.join("\n");
}
