import type {
  ComponentDef,
  ComponentLookup,
  PrefabFile,
  PrefabFileV1,
} from "@emptysock/engine";
import { parsePrefabFiles, prefabComponentDefs } from "@emptysock/engine";

/**
 * ENGINE_DESIGN.md §13.4 — the offline half of "JSON with generated `.d.ts`
 * types alongside". This lives in `packages/toolchain`, not
 * `packages/engine`, because it is pure codegen: it reads a project's
 * `.prefab.json` files plus the real `ComponentDef`s the project registered
 * (for their field *types*, which JSON alone can't carry) and emits a
 * `.d.ts` string — no engine runtime behaviour, no `Scene`/`World` involved.
 * `packages/engine/src/ecs/SceneFile.ts` owns the other half: parsing that
 * same JSON into a live `PrefabDef` a running `Scene` can actually spawn.
 * Both halves share `ComponentLookup`/`PrefabFile` from `@emptysock/engine`
 * so a field can't drift between "what spawns" and "what autocompletes".
 *
 * This function is the codegen step itself, callable from either caller
 * `RELEASE_PASS.md` calls out:
 *  - a toolchain CLI build step (not yet wired into `cli.ts` — see the
 *    follow-up noted in `RELEASE_PASS.md`)
 *  - an IDE auto-save hook (not yet wired into `apps/ide`'s editor save
 *    pipeline — same follow-up, left as a note rather than reaching into
 *    `apps/ide/src/services` in this pass to avoid scope creep on a
 *    concurrently-edited surface)
 */

/** TypeScript's own primitive/array/object literal syntax for one runtime value, for codegen purposes only. */
function tsTypeOf(value: unknown): string {
  if (value === null) return "null";
  if (value === undefined) return "undefined";
  if (typeof value === "string") return "string";
  if (typeof value === "number") return "number";
  if (typeof value === "boolean") return "boolean";
  if (Array.isArray(value)) {
    if (value.length === 0) return "unknown[]";
    return `Array<${tsTypeOf(value[0])}>`;
  }
  if (typeof value === "object") {
    const entries = Object.entries(value as Record<string, unknown>)
      .map(([k, v]) => `${JSON.stringify(k)}: ${tsTypeOf(v)}`)
      .join("; ");
    return `{ ${entries} }`;
  }
  return "unknown";
}

/** Merges every component's default field shape a prefab (with its `extends`) touches into one flat field->type map. */
function mergedPropShape(defs: readonly ComponentDef[]): Map<string, string> {
  const shape = new Map<string, string>();
  for (const def of defs) {
    const defaults = def.createDefaults();
    for (const [field, value] of Object.entries(defaults)) {
      shape.set(field, tsTypeOf(value));
    }
  }
  return shape;
}

/** A valid TypeScript identifier for a prefab's ambient `declare const` — non-identifier characters are stripped. */
function toIdentifier(prefabName: string): string {
  const cleaned = prefabName.replace(/[^A-Za-z0-9_$]/g, "_");
  return /^[A-Za-z_$]/.test(cleaned) ? cleaned : `_${cleaned}`;
}

export interface PrefabCodegenOptions {
  /** Import specifier the emitted `.d.ts` uses for `PrefabDef` — defaults to `@emptysock/engine`. */
  readonly engineImportSpecifier?: string;
}

/**
 * Reads a project's `.prefab.json` file contents plus its registered
 * component lookup, and emits a `.d.ts` string declaring one
 * `PrefabDef<{...}>`-typed ambient `const` per prefab — so
 * `scene.spawn(EnemyPrefab, props)` autocompletes `props` against that
 * prefab's actual, merged component field shape (defaults from every
 * component it declares, plus everything it `extends`).
 *
 * The emitted file is meant to sit alongside the prefab JSON and be
 * `import`ed (its `declare const`s, not its types, are what game code
 * actually uses) — see `packages/toolchain/src/__tests__/prefabCodegen.test.ts`
 * for the exact shape asserted.
 */
export function generatePrefabTypes(
  files: readonly (PrefabFile | PrefabFileV1)[],
  lookup: ComponentLookup,
  options: PrefabCodegenOptions = {},
): string {
  const importSpecifier = options.engineImportSpecifier ?? "@emptysock/engine";
  const prefabs = parsePrefabFiles(files, lookup);

  const header = [
    "// AUTO-GENERATED by @emptysock/toolchain's prefab codegen — do not edit by hand.",
    "// Regenerated on every IDE save and by the toolchain build step (ENGINE_DESIGN.md §13.4).",
    `import type { PrefabDef } from "${importSpecifier}";`,
    "",
  ].join("\n");

  const body = files
    .map((file) => {
      const prefab = prefabs.get(file.prefabName);
      if (prefab === undefined) {
        throw new Error(
          `generatePrefabTypes: "${file.prefabName}" failed to parse.`,
        );
      }
      const shape = mergedPropShape(prefabComponentDefs(prefab));
      const fields =
        shape.size === 0
          ? ""
          : [...shape.entries()]
              .map(([field, type]) => `  ${JSON.stringify(field)}: ${type};`)
              .join("\n");
      const propsType =
        shape.size === 0 ? "Record<string, never>" : `{\n${fields}\n}`;
      const identifier = toIdentifier(file.prefabName);
      return `export declare const ${identifier}: PrefabDef<${propsType}>;`;
    })
    .join("\n\n");

  return `${header}${body}\n`;
}
