import type { Vec2 } from "../core/Entity.js";
export type { Vec2 };

export interface NavPolygon {
  readonly id: number;
  /** Convex polygon vertices in order. */
  readonly vertices: ReadonlyArray<Vec2>;
  readonly centroid: Vec2;
  /** IDs of adjacent walkable polygons. */
  readonly neighbours: ReadonlyArray<number>;
}

export interface NavMeshData {
  readonly polygons: ReadonlyArray<NavPolygon>;
}

interface AStarNode {
  id: number;
  g: number;
  h: number;
  f: number;
  parent: number | null;
}

// ---------------------------------------------------------------------------
// Binary min-heap keyed by AStarNode.f
// ---------------------------------------------------------------------------
// Replaces the O(n) linear scan that previously found the open-list node with
// the smallest f-score on every A* iteration.  push() and pop() both run in
// O(log n), making the overall A* complexity O(V log V) instead of O(V²).
//
// Lazy deletion handles updates: when a shorter path to a node is found the
// improved AStarNode is pushed again.  Stale copies (higher g) are discarded
// when they surface during pop() via the bestG check in findPath() — no
// heap-index map is needed.

class AStarMinHeap {
  private readonly _data: AStarNode[] = [];

  get size(): number {
    return this._data.length;
  }

  push(node: AStarNode): void {
    this._data.push(node);
    this._siftUp(this._data.length - 1);
  }

  /** Removes and returns the node with the smallest f. Caller must ensure size > 0. */
  pop(): AStarNode {
    const top = this._data[0] as AStarNode;
    const last = this._data.pop() as AStarNode;
    if (this._data.length > 0) {
      this._data[0] = last;
      this._siftDown(0);
    }
    return top;
  }

  private _siftUp(idx: number): void {
    const data = this._data;
    while (idx > 0) {
      const parent = (idx - 1) >> 1;
      if ((data[parent] as AStarNode).f <= (data[idx] as AStarNode).f) break;
      const tmp = data[parent] as AStarNode;
      data[parent] = data[idx] as AStarNode;
      data[idx] = tmp;
      idx = parent;
    }
  }

  private _siftDown(idx: number): void {
    const data = this._data;
    const n = data.length;
    for (;;) {
      let smallest = idx;
      const l = 2 * idx + 1;
      const r = 2 * idx + 2;
      if (l < n && (data[l] as AStarNode).f < (data[smallest] as AStarNode).f)
        smallest = l;
      if (r < n && (data[r] as AStarNode).f < (data[smallest] as AStarNode).f)
        smallest = r;
      if (smallest === idx) break;
      const tmp = data[idx] as AStarNode;
      data[idx] = data[smallest] as AStarNode;
      data[smallest] = tmp;
      idx = smallest;
    }
  }
}

/**
 * NavMesh pathfinding for free-form 2D movement.
 * Load a NavMeshData (generated by your level editor or Tiled plugin) then
 * call findPath() to get a smoothed waypoint list.
 */
export class NavMeshSystem {
  private readonly _polygons: Map<number, NavPolygon> = new Map();

  load(data: NavMeshData): void {
    this._polygons.clear();
    for (const poly of data.polygons) {
      this._polygons.set(poly.id, poly);
    }
  }

  /**
   * Find a path between two world-space points.
   * Returns an array of waypoints starting at `from` and ending at `to`.
   * Returns [] if no path exists.
   */
  findPath(from: Vec2, to: Vec2): Vec2[] {
    const startPoly = this._nearestPolygon(from);
    const endPoly = this._nearestPolygon(to);
    if (startPoly === null || endPoly === null) return [];
    if (startPoly.id === endPoly.id) return [from, to];

    const open = new AStarMinHeap();
    const closed = new Set<number>();
    const bestG = new Map<number, number>(); // best known g-score per polygon id
    const cameFrom = new Map<number, number | null>();

    const h = (poly: NavPolygon): number =>
      this._dist(poly.centroid, endPoly.centroid);

    const startNode: AStarNode = {
      id: startPoly.id,
      g: 0,
      h: h(startPoly),
      f: h(startPoly),
      parent: null,
    };
    open.push(startNode);
    bestG.set(startPoly.id, 0);
    cameFrom.set(startPoly.id, null);

    while (open.size > 0) {
      const current = open.pop();

      // Lazy deletion: a stale copy surfaces when a shorter path was found and
      // a better node was pushed without removing this one.  Skip it.
      const knownG = bestG.get(current.id);
      if (knownG !== undefined && current.g > knownG) continue;

      if (closed.has(current.id)) continue;
      closed.add(current.id);

      if (current.id === endPoly.id) {
        return this._reconstructPath(from, to, current.id, cameFrom);
      }

      const poly = this._polygons.get(current.id);
      if (poly === undefined) continue;

      for (const neighbourId of poly.neighbours) {
        if (closed.has(neighbourId)) continue;
        const neighbour = this._polygons.get(neighbourId);
        if (neighbour === undefined) continue;

        const g = current.g + this._dist(poly.centroid, neighbour.centroid);
        const prevBestG = bestG.get(neighbourId);
        if (prevBestG === undefined || g < prevBestG) {
          const nh = h(neighbour);
          open.push({
            id: neighbourId,
            g,
            h: nh,
            f: g + nh,
            parent: current.id,
          });
          bestG.set(neighbourId, g);
          cameFrom.set(neighbourId, current.id);
        }
      }
    }

    return [];
  }

  private _reconstructPath(
    from: Vec2,
    to: Vec2,
    endId: number,
    cameFrom: Map<number, number | null>,
  ): Vec2[] {
    const polyIds: number[] = [];
    let cur: number | null = endId;
    while (cur !== null) {
      polyIds.unshift(cur);
      cur = cameFrom.get(cur) ?? null;
    }

    const waypoints: Vec2[] = [from];
    for (let i = 1; i < polyIds.length; i++) {
      const pid = polyIds[i];
      if (pid === undefined) continue;
      const poly = this._polygons.get(pid);
      if (poly !== undefined) waypoints.push(poly.centroid);
    }
    waypoints.push(to);
    return waypoints;
  }

  private _nearestPolygon(point: Vec2): NavPolygon | null {
    let nearest: NavPolygon | null = null;
    let minDist = Infinity;
    for (const poly of this._polygons.values()) {
      if (this._pointInPolygon(point, poly.vertices)) return poly;
      const d = this._dist(point, poly.centroid);
      if (d < minDist) {
        minDist = d;
        nearest = poly;
      }
    }
    return nearest;
  }

  private _pointInPolygon(p: Vec2, verts: ReadonlyArray<Vec2>): boolean {
    let inside = false;
    for (let i = 0, j = verts.length - 1; i < verts.length; j = i++) {
      const vi = verts[i];
      const vj = verts[j];
      if (vi === undefined || vj === undefined) continue;
      if (
        vi.y > p.y !== vj.y > p.y &&
        p.x < ((vj.x - vi.x) * (p.y - vi.y)) / (vj.y - vi.y) + vi.x
      ) {
        inside = !inside;
      }
    }
    return inside;
  }

  private _dist(a: Vec2, b: Vec2): number {
    return Math.sqrt((a.x - b.x) ** 2 + (a.y - b.y) ** 2);
  }

  update(_dt: number): void {
    /* on-demand; no per-frame work */
  }
}
