import type { Vec2 } from "../core/Entity.js";
import { AStarSearch } from "../core/AStarSearch.js";
export type { Vec2 };

export interface NavPolygon {
  readonly id: number;
  /** Convex polygon vertices in order. */
  readonly vertices: ReadonlyArray<Vec2>;
  readonly centroid: Vec2;
  /** IDs of adjacent walkable polygons. */
  readonly neighbours: ReadonlyArray<number>;
}

export interface NavMeshData {
  readonly polygons: ReadonlyArray<NavPolygon>;
}

/**
 * NavMesh pathfinding for free-form 2D movement.
 * Load a NavMeshData (generated by your level editor or Tiled plugin) then
 * call findPath() to get a smoothed waypoint list.
 */
export class NavMeshSystem {
  private readonly _polygons: Map<number, NavPolygon> = new Map();

  load(data: NavMeshData): void {
    this._polygons.clear();
    for (const poly of data.polygons) {
      this._polygons.set(poly.id, poly);
    }
  }

  /**
   * Find a path between two world-space points.
   * Returns an array of waypoints starting at `from` and ending at `to`.
   * Returns [] if no path exists.
   */
  findPath(from: Vec2, to: Vec2): Vec2[] {
    const startPoly = this._nearestPolygon(from);
    const endPoly = this._nearestPolygon(to);
    if (startPoly === null || endPoly === null) return [];
    if (startPoly.id === endPoly.id) return [from, to];

    const result = AStarSearch<NavPolygon>({
      start: startPoly,
      isGoal: (poly) => poly.id === endPoly.id,
      heuristic: (poly) => this._dist(poly.centroid, endPoly.centroid),
      key: (poly) => poly.id,
      neighbours: (poly) => {
        const edges: Array<{ node: NavPolygon; cost: number }> = [];
        for (const neighbourId of poly.neighbours) {
          const neighbour = this._polygons.get(neighbourId);
          if (neighbour === undefined) continue;
          edges.push({
            node: neighbour,
            cost: this._dist(poly.centroid, neighbour.centroid),
          });
        }
        return edges;
      },
    });

    if (!result.found) return [];
    return this._toWaypoints(from, to, result.path);
  }

  private _toWaypoints(
    from: Vec2,
    to: Vec2,
    polyPath: ReadonlyArray<NavPolygon>,
  ): Vec2[] {
    const waypoints: Vec2[] = [from];
    for (let i = 1; i < polyPath.length; i++) {
      const poly = polyPath[i];
      if (poly !== undefined) waypoints.push(poly.centroid);
    }
    waypoints.push(to);
    return waypoints;
  }

  private _nearestPolygon(point: Vec2): NavPolygon | null {
    let nearest: NavPolygon | null = null;
    let minDist = Infinity;
    for (const poly of this._polygons.values()) {
      if (this._pointInPolygon(point, poly.vertices)) return poly;
      const d = this._dist(point, poly.centroid);
      if (d < minDist) {
        minDist = d;
        nearest = poly;
      }
    }
    return nearest;
  }

  private _pointInPolygon(p: Vec2, verts: ReadonlyArray<Vec2>): boolean {
    let inside = false;
    for (let i = 0, j = verts.length - 1; i < verts.length; j = i++) {
      const vi = verts[i];
      const vj = verts[j];
      if (vi === undefined || vj === undefined) continue;
      if (
        vi.y > p.y !== vj.y > p.y &&
        p.x < ((vj.x - vi.x) * (p.y - vi.y)) / (vj.y - vi.y) + vi.x
      ) {
        inside = !inside;
      }
    }
    return inside;
  }

  private _dist(a: Vec2, b: Vec2): number {
    return Math.sqrt((a.x - b.x) ** 2 + (a.y - b.y) ** 2);
  }

  update(_dt: number): void {
    /* on-demand; no per-frame work */
  }
}
