export interface Vec2 { x: number; y: number; }

export interface NavPolygon {
  readonly id: number;
  /** Convex polygon vertices in order. */
  readonly vertices: ReadonlyArray<Vec2>;
  readonly centroid: Vec2;
  /** IDs of adjacent walkable polygons. */
  readonly neighbours: ReadonlyArray<number>;
}

export interface NavMeshData {
  readonly polygons: ReadonlyArray<NavPolygon>;
}

interface AStarNode {
  id: number;
  g: number;
  h: number;
  f: number;
  parent: number | null;
}

/**
 * NavMesh pathfinding for free-form 2D movement.
 * Load a NavMeshData (generated by your level editor or Tiled plugin) then
 * call findPath() to get a smoothed waypoint list.
 */
export class NavMeshSystem {
  private readonly _polygons: Map<number, NavPolygon> = new Map();

  load(data: NavMeshData): void {
    this._polygons.clear();
    for (const poly of data.polygons) {
      this._polygons.set(poly.id, poly);
    }
  }

  /**
   * Find a path between two world-space points.
   * Returns an array of waypoints starting at `from` and ending at `to`.
   * Returns [] if no path exists.
   */
  findPath(from: Vec2, to: Vec2): Vec2[] {
    const startPoly = this._nearestPolygon(from);
    const endPoly   = this._nearestPolygon(to);
    if (startPoly === null || endPoly === null) return [];
    if (startPoly.id === endPoly.id) return [from, to];

    const open   = new Map<number, AStarNode>();
    const closed = new Set<number>();
    const cameFrom = new Map<number, number | null>();

    const h = (poly: NavPolygon): number => this._dist(poly.centroid, endPoly.centroid);

    const startNode: AStarNode = { id: startPoly.id, g: 0, h: h(startPoly), f: h(startPoly), parent: null };
    open.set(startPoly.id, startNode);
    cameFrom.set(startPoly.id, null);

    while (open.size > 0) {
      let current: AStarNode | null = null;
      for (const node of open.values()) {
        if (current === null || node.f < current.f) current = node;
      }
      if (current === null) break;

      if (current.id === endPoly.id) {
        return this._reconstructPath(from, to, current.id, cameFrom);
      }

      open.delete(current.id);
      closed.add(current.id);

      const poly = this._polygons.get(current.id);
      if (poly === undefined) continue;

      for (const neighbourId of poly.neighbours) {
        if (closed.has(neighbourId)) continue;
        const neighbour = this._polygons.get(neighbourId);
        if (neighbour === undefined) continue;

        const g = current.g + this._dist(poly.centroid, neighbour.centroid);
        const existing = open.get(neighbourId);
        if (existing === undefined || g < existing.g) {
          const nh = h(neighbour);
          open.set(neighbourId, { id: neighbourId, g, h: nh, f: g + nh, parent: current.id });
          cameFrom.set(neighbourId, current.id);
        }
      }
    }

    return [];
  }

  private _reconstructPath(from: Vec2, to: Vec2, endId: number, cameFrom: Map<number, number | null>): Vec2[] {
    const polyIds: number[] = [];
    let cur: number | null = endId;
    while (cur !== null) {
      polyIds.unshift(cur);
      cur = cameFrom.get(cur) ?? null;
    }

    const waypoints: Vec2[] = [from];
    for (let i = 1; i < polyIds.length; i++) {
      const pid = polyIds[i];
      if (pid === undefined) continue;
      const poly = this._polygons.get(pid);
      if (poly !== undefined) waypoints.push(poly.centroid);
    }
    waypoints.push(to);
    return waypoints;
  }

  private _nearestPolygon(point: Vec2): NavPolygon | null {
    let nearest: NavPolygon | null = null;
    let minDist = Infinity;
    for (const poly of this._polygons.values()) {
      if (this._pointInPolygon(point, poly.vertices)) return poly;
      const d = this._dist(point, poly.centroid);
      if (d < minDist) { minDist = d; nearest = poly; }
    }
    return nearest;
  }

  private _pointInPolygon(p: Vec2, verts: ReadonlyArray<Vec2>): boolean {
    let inside = false;
    for (let i = 0, j = verts.length - 1; i < verts.length; j = i++) {
      const vi = verts[i];
      const vj = verts[j];
      if (vi === undefined || vj === undefined) continue;
      if ((vi.y > p.y) !== (vj.y > p.y) &&
          p.x < ((vj.x - vi.x) * (p.y - vi.y)) / (vj.y - vi.y) + vi.x) {
        inside = !inside;
      }
    }
    return inside;
  }

  private _dist(a: Vec2, b: Vec2): number {
    return Math.sqrt((a.x - b.x) ** 2 + (a.y - b.y) ** 2);
  }

  update(_dt: number): void { /* on-demand; no per-frame work */ }
}
